### ISSUE TITLE
The `IFlashMintReceiver` callback should use a more generic function name.

### ISSUE THREAD

**Issue by alcueca** [sky-ecosystem/mips#132]
`execute` is very generic and could clash with functionality on the receiver or on other callback interfaces.

I would recommend using `onFlashMint`, since the interface will likely be reused by other projects outside MakerDAO.

**Comment by hexonaut** [comment]
Thanks for opening these, but it's in the wrong repository.

I've opened a PR to implement this change: https://github.com/hexonaut/dss-flash/pull/8
