### ISSUE TITLE
The `IFlashMintReceiver` callback should take a `sender` parameter.

### ISSUE THREAD

**Issue by alcueca** [sky-ecosystem/mips#133]
The `receiver` will always be a contract that needs to know the user that originated the transaction, and only `flash.sol` can safely say who that is. The callback interface should include a `sender` parameter, filled by `flash.mint` with `msg.sender`.

`IFlashMintReceiver(_receiver).onFlashMint(msg.sender, _amount, fee, _data);`

Leaving to the sender to fill `data` with the account to manipulate on the callback would be unsafe.

There are other mechanisms to safely pass the target account, if `sender` would not be an EOA. Namely you can either store the address of the target account in a state variable in the `receiver`, or use off-chain signatures embedded in `data`. Both methods are more complex and expensive than just having `flash.sol` state who is the `sender`.

**Comment by hexonaut** [comment]
This is an interesting point. Can you re-open this in the dss-flash repo: https://github.com/hexonaut/dss-flash/issues ?

Thanks.

**Comment by CPSTL** [comment]
@albertocuestacanada Closing this issue - please see Sam's above comment to continue the conversation.
