### ISSUE TITLE
Should MIP16c3 be moved into MIP0 as MIP0c14?

### ISSUE THREAD

**Issue by Davidutro** [sky-ecosystem/mips#154]
I find it super random that _[MIP16c3: Limiting Governance to MIP-defined processes](https://github.com/makerdao/mips/blob/master/MIP16/mip16.md#mip16c3-limiting-governance-to-mip-defined-processes)_ is in the Weekly Governance Cycle MIP. It sounds like this is a bit more fundamental to the overall [MIPs framework as presented in MIP0.](https://github.com/makerdao/mips/blob/master/MIP0/mip0.md)

Curious to hear thoughts for or against, and why.

Should MIP16c3 be moved into MIP0 as MIP0c14?

**Comment by CPSTL** [comment]
@Davidutro Closing this issue as it has not been active since January. Please feel free to re-open it if you want to resurrect the improvement discussion.
