### ISSUE TITLE
MIP 16 references MIP 3 which is superceded by MIP 51

### ISSUE THREAD

**Issue by jpritikin** [sky-ecosystem/mips#372]
[MIP51](https://mips.makerdao.com/mips/details/MIP51) is the new monthly gov cycle that supercedes [MIP3](https://mips.makerdao.com/mips/details/MIP3). However, [MIP16](https://mips.makerdao.com/mips/details/MIP16) still refers to MIP3.

A quick `git grep 'MIP3\W'` also turns up,

```
MIP11/mip11.md:Dependencies: MIP0, MIP3, MIP7
MIP12/mip12.md:Dependencies: MIP0, MIP3, MIP7
```

Want a pull request to fix this?

**Comment by blimpa** [comment]
Hey, Joshua. I'll be working on this over the weekend. Thank you :)
