### ISSUE TITLE
Provisional Technical Spec for MIPs Site

### ISSUE THREAD

**Issue by andytudhope** [sky-ecosystem/mips#69]
# Website Specification

This is an initial specification for how the MakerDAO MIPs site ought to handle the process for **educating** people on what MIPs are; **showing** them how to submit MIPs; and setting up a sustainable **process** for handling and **displaying** in process, accepted and rejected MIPs.

## Initial Template

An example site can be found [here](https://dai-gnostics.com/). It is built off [this branch](https://github.com/andytudhope/mips/tree/r2d). All specifications below will refer to this codebase.

We have selected the Gatsby starter purpose-built for the MakerDAO community portal. We have done so for a number of reasons:

1. Coherent design + technical systems across all community-led project/products.
2. Ease of contributions, and more work to contribute to, for comm-dev developers.
3. Reusable code is cool.

### Overview

The new portal is great, however, the way it constructs - in particular - the sidenav content poses a problem for the MIPs site. Currently, the sidenav for any given route is generated for any and all files in that specific directory. So, the sidenav for "Learn" will display all the files under `learn` in the order you have specified. It simply runs a [graphql query](https://github.com/andytudhope/mips/blob/r2d/src/modules/navigation/calculateTreeData.js#L109) at build time and spits out each file as a nav item. We'll need a considerably more intelligent query/set of queries.

### Repo Structure

The repo structure for MIPs is different. We want each MIP to have its own directory, such that the MIP and any templates or subproposals associated with it live in one, coherent place. This is especially useful when people submit new MIPs as PRs to the repo. Therefore, we need to fetch the sidenav organisation from the frontmatter **status** of each `mip*.md` file. 

1. If the `status == accepted`, display it under the "Accepted" route. Ideally, we can generate a table on the `accepted/index.mdx` file of all Accepted MIPs, with their date, title, link.
2. If the `status == RFC`, display it under the "In Progress" route. Ideally, we can generate a table on the `in-progress/index.mdx` file of all In Progress MIPs, with their date, title, link. (Yes, there are many stages to "RFC", but we'll keep it simple for v1.)

### Learn

The Learn route needs to fulfill two functions:

1. It will host a bunch of static content for educating people about how the MIPs process works, how to get involved, and what the aims are etc. The current sidenav algorithm would suffice for this, but:
2. It needs to host all the templates and subproposals from each relevant MIP directory as a part of showing people how to get involved and submit different SPs etc.

- This can be achieved either through a static json file (the easiest option), or a more coherent graphql query at build time, seeing as we need to update it anyway. 
- The issue with the json file approach is translations and maintainer overhead. The issue with any other approach is considerable complexity of any query which would fulfill our needs.

### Collateral Onboarding

1. This is an important - and likely the most active - part of the MIPs process, and so it gets it's own route. Technically, it's just MIP6c2 Sub Proposals. However, we'll need a sidenav that splits each application into `accepted`, `in progress` or `rejected`, like we have the header navigation, but for collateral applications specifically. 
2. This is illustrated by the current directory setup in the [initial repo](https://github.com/andytudhope/mips/tree/r2d/content/en/collateral).

### Sub-proposals

Sub-proposals will be submitted as PRs to the specific `subproposals` directory, i.e. [here](https://github.com/andytudhope/mips/tree/r2d/content/en/subproposals). Once the front matter `status` has been changed from `RFC` to `Accepted`, the same logic should follow as for MIPs, except that they all need to be grouped under a collapsible menu item in the sidenav in either "In Progress" or "Accepted", depending on what their current status is.

### Outputs

**Critical**:

1. A sidenav algorithm that sorts any `mip*.md` file into either the "Accepted" or "In Progress" route, and orders them according to number. We'll worry about rejected MIPs in v2.
2. Another (part to the) algorithm that allows us to do a static query/use a json file to organise content under the Learn route.
3. A third (part to the) algorithm which sorts "Collateral Onboarding" applications specifically into their own route, divided into three sections: "In Progress", "Accepted" and "Rejected".

This all ensures two critical features:

1. The repo structure stays largely the same, no critical files change names, and each MIP keeps its own directory, for ease of navigating in GH + submitting new MIPs.
2. MIP Editors just need to change 1 `status` field in the frontmatter of a single MIP file (or collateral application) in order for it to be updated across the site and appear in the right place.

**Bonus**:

1. A auto-generated table for "Accepted" and "In Progress" index pages to give an easy overview which need not be manually maintained.

**Comment by LongForWisdom** [comment]
> We want each MIP to have its own directory, such that the MIP and any templates or subproposals associated with it live in one, coherent place.

>Sub-proposals will be submitted as PRs to the specific subproposals directory, i.e. here. 

Are these two points not contradictory? Would we need to change the MIPs Repo structure from it's current structure in order to implement this as described?

**Comment by LongForWisdom** [comment]
Ah, I think I get it. You'd need to have a list of subproposals in the frontend repo that was kept up to date?
